Paper Pipeline Protoyping

In [55]:
# psql -h localhost -d research_platform -U postgres -f platform_schema.sql

In [56]:
import torch
print(f"PyTorch version: {torch.__version__}")
torch.cuda.is_available()

PyTorch version: 2.7.0

True

In [57]:
from langchain_huggingface import HuggingFaceEmbeddings
from sentence_transformers import SentenceTransformer
from langchain_postgres import PGVector
import pandas as pd
from sqlalchemy import create_engine
import json
import psycopg
import ray
import dask.dataframe as dd
import dask
import modin.pandas as mdf
import os
import polars as pl
from pgvector.sqlalchemy import Vector
from dotenv import load_dotenv
load_dotenv()
ray.init(num_gpus=1, ignore_reinit_error=True)

2025-06-09 21:25:01,487	INFO worker.py:1718 -- Calling ray.init() again after it has already been called.

RayContext(dashboard_url='', python_version='3.12.10', ray_version='2.46.0', ray_commit='{{RAY_COMMIT_SHA}}')

In [58]:
# list the available CPU cores
total_cores = ray.cluster_resources()['CPU']
print(f"Total CPU cores available: {total_cores}")
ray.available_resources()

Total CPU cores available: 128.0

{'node:192.168.50.241': 1.0,
 'accelerator_type:G': 1.0,
 'node:__internal_head__': 1.0,
 'CPU': 128.0,
 'memory': 76222264116.0,
 'object_store_memory': 32666684620.0,
 'GPU': 1.0}

In [59]:
def create_embedding(model, sentences):
  """
  Create embeddings for a list of sentences using the specified model.
  
  Args:
      model: The model to use for creating embeddings.
      sentences: A list of sentences to embed.
  
  Returns:
      A list of embeddings for the input sentences.
  """
  embeddings = model.encode(sentences, convert_to_tensor=True)
  return embeddings

In [60]:
arxiv_bert_model = SentenceTransformer('ArtifactAI/arxiv-distilroberta-base-GenQ', device='cuda' if torch.cuda.is_available() else 'cpu')
# output_embeddings = create_embedding(
#   model=arix_bert_model,
#   sentences=["This is a test sentence", "This is another test sentence"]
# )

In [61]:
@ray.remote(num_gpus=1)
def process_paper_metadata_embeddings(model,dataframe):
  """
  Process a JSON file containing paper metadata and extract relevant information.
  
  """
  dataframe["embedding"] = dataframe.apply(
    lambda row: create_embedding(
      model,
      row['abstract'],
    ).tolist(),
    axis=1
  )
  dataframe = dataframe.rename(columns={'abstract': 'context'})
  dataframe = dataframe.rename(columns={'id': 'paper_id'})
  dataframe = dataframe[["paper_id", "embedding", "context"]]
  
  return dataframe

In [62]:
async def store_row_in_postgres(connection, row):
  """
  Store a row of data in the PostgreSQL database.
  
  Args:
      connection: The database connection object.
      row: The row of data to store.
  
  """
  paper_id = row['paper_id']
  embedding = row['embedding']
  context = row['context']
  
  # Insert the data into the database
  await connection.execute(
    "INSERT INTO paper_vector_db (paper_id, embedding, context) VALUES (%s, %s, %s)",
    (paper_id, embedding, context),
  )
  await connection.commit()

In [63]:
connection = await psycopg.AsyncConnection.connect(
  os.environ['SELF_HOSTED_POSTGRES_CONNECTION']
)

### Parallelizing paper upload

Use Modin Dataframes for parallel processing, wraps pandas in ray context

In [64]:
def fetch_computer_science_paper_metadata(dataframe):
  # 
  computer_science_paper_metadata_mdf = dataframe[
    dataframe['categories'].fillna('').str.contains('cs.', case=False, na=False)
  ]
  return computer_science_paper_metadata_mdf

In [65]:
def process_paper_metadata_papers(dataframe):
#  Index(['paper_id', 'submitter', 'authors', 'title', 'comments', 'journal-ref',
#        'doi', 'report-no', 'categories', 'license', 'abstract', 'versions',
#        'update_date', 'authors_parsed'],
#       dtype='object')
  print("Initial keys",dataframe.keys())
  dataframe = dataframe.rename(columns={'id': 'paper_id'})
  dataframe = dataframe.rename(columns={'report-no': 'report_number'})
  dataframe = dataframe.fillna('').astype(str)
  print("Output keys",dataframe.keys())
  dataframe = dataframe[["paper_id", "title", "abstract", "doi", "report_number"]]
  return dataframe

In [66]:
def process_paper_document_metadata(dataframe):
  
  dataframe = dataframe.rename(columns={'id': 'paper_id'})
  dataframe = dataframe.rename(columns={'title': 'file_name'})
  dataframe["owner_id"] = "public"
  dataframe["group_id"] = "public"
  dataframe["url"] = dataframe.apply(lambda row: f"/arxiv.org/pdf/{row['paper_id']}", axis=1)
  print(dataframe.keys())
  return dataframe[["paper_id", "owner_id", "group_id", "file_name", "url"]]

In [67]:
paper_metadata_df = pd.read_json('arxiv-metadata-oai-snapshot.json', lines=True).head(10)

In [68]:
display(paper_metadata_df.head())

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
0,0704.0001,Pavel Nadolsky,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",Calculation of prompt diphoton production cros...,"37 pages, 15 figures; published version","Phys.Rev.D76:013009,2007",10.1103/PhysRevD.76.013009,ANL-HEP-PR-07-12,hep-ph,None,A fully differential calculation in perturba...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2008-11-26,"[[Balázs, C., ], [Berger, E. L., ], [Nadolsky,..."
1,0704.0002,Louis Theran,Ileana Streinu and Louis Theran,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,None,None,None,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[[Streinu, Ileana, ], [Theran, Louis, ]]"
2,0704.0003,Hongjun Pan,Hongjun Pan,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",None,None,None,physics.gen-ph,None,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[[Pan, Hongjun, ]]"
3,0704.0004,David Callan,David Callan,A determinant of Stirling cycle numbers counts...,11 pages,None,None,None,math.CO,None,We show that a determinant of Stirling cycle...,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2007-05-23,"[[Callan, David, ]]"
4,0704.0005,Alberto Torchinsky,Wael Abu-Shammala and Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,None,"Illinois J. Math. 52 (2008) no.2, 681-689",None,None,math.CA math.FA,None,In this paper we show how to compute the $\L...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2013-10-15,"[[Abu-Shammala, Wael, ], [Torchinsky, Alberto, ]]"

In [69]:
from sqlalchemy import text

# add vector support to the engine


engine = create_engine(os.environ["SELF_HOSTED_POSTGRES_CONNECTION"])


alchemy_connection = engine.connect()
alchemy_connection.execute(text('CREATE EXTENSION IF NOT EXISTS vector'))

In [70]:
cs_paper_df = fetch_computer_science_paper_metadata(paper_metadata_df)
cs_paper_mdf = mdf.DataFrame(cs_paper_df)

paper vector db upload

In [79]:
embedding_mdf = ray.get(process_paper_metadata_embeddings.remote(arxiv_bert_model, paper_metadata_df))
async def insert_embeddings(connection, embedding_mdf):
  records = [
    (row['paper_id'], row['embedding'], row['context'])
    for _, row in embedding_mdf.iterrows()
  ]
  async with connection.cursor() as cur:
    await cur.executemany(
      "INSERT INTO paper_vector_db (paper_id, embedding, context) VALUES (%s, %s, %s)",
      records
    )
    await connection.commit()

In [80]:
await insert_embeddings(connection=connection,embedding_mdf=embedding_mdf)

In [ ]:
process_paper_metadata_papers(cs_paper_df.copy()).to_sql('paper_metadata',alchemy_connection, if_exists='replace', index=False)

Initial keys Index(['id', 'submitter', 'authors', 'title', 'comments', 'journal-ref', 'doi',
       'report-no', 'categories', 'license', 'abstract', 'versions',
       'update_date', 'authors_parsed'],
      dtype='object')
Output keys Index(['paper_id', 'submitter', 'authors', 'title', 'comments', 'journal-ref',
       'doi', 'report_number', 'categories', 'license', 'abstract', 'versions',
       'update_date', 'authors_parsed'],
      dtype='object')

2

In [ ]:
display(cs_paper_mdf.keys())

Index(['id', 'submitter', 'authors', 'title', 'comments', 'journal-ref', 'doi',
       'report-no', 'categories', 'license', 'abstract', 'versions',
       'update_date', 'authors_parsed'],
      dtype='object')

In [ ]:
process_paper_document_metadata(cs_paper_df.copy()).to_sql("documents", con=alchemy_connection, if_exists="replace", index=False)

Index(['paper_id', 'submitter', 'authors', 'file_name', 'comments',
       'journal-ref', 'doi', 'report-no', 'categories', 'license', 'abstract',
       'versions', 'update_date', 'authors_parsed', 'owner_id', 'group_id',
       'url'],
      dtype='object')

2

In [ ]:
display(cs_paper_mdf.head())

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
1,0704.0002,Louis Theran,Ileana Streinu and Louis Theran,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,None,None,None,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[[Streinu, Ileana, ], [Theran, Louis, ]]"
2,0704.0003,Hongjun Pan,Hongjun Pan,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",None,None,None,physics.gen-ph,None,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[[Pan, Hongjun, ]]"

In [ ]:
ray.shutdown()

I0000 00:00:1749528091.277336   48089 chttp2_transport.cc:1182] ipv4:192.168.50.241:60342: Got goaway [2] err=UNAVAILABLE:GOAWAY received; Error code: 2; Debug Text: Cancelling all calls {grpc_status:14, http2_error:2, created_time:"2025-06-09T21:01:31.27733162-07:00"}

In [ ]:
sync_connection = psycopg.connect(
  os.environ['SELF_HOSTED_POSTGRES_CONNECTION']
)
result =sync_connection.execute(
  "SELECT * FROM paper_vector_db;"
)
result_dict = result.fetchall()

In [ ]:
display(result_dict[0][1])

'{-0.02221376821398735,-0.02284185215830803,0.017939966171979904,-0.5473503470420837,-0.17219851911067963,-0.14693816006183624,0.02166121080517769,0.03382785990834236,0.05365683510899544,-0.06282669305801392,0.35840752720832825,-0.16424213349819183,0.28802913427352905,-0.3820122480392456,0.017693262547254562,-0.18410398066043854,0.2947666049003601,-0.7180113792419434,0.07303538918495178,0.46925801038742065,0.48016849160194397,-1.0009331703186035,0.10231275111436844,-0.3701360821723938,0.6909980177879333,0.11818594485521317,-0.19581782817840576,-0.054143037647008896,0.5461544990539551,-1.0881317853927612,0.2266409695148468,0.028451768681406975,-0.0926627367734909,-0.1781274825334549,-0.18542271852493286,-0.15120965242385864,-0.16811080276966095,0.27875813841819763,-0.5428684949874878,-0.26670345664024353,0.31100139021873474,-0.7332471609115601,0.14510445296764374,-0.22941753268241882,-0.5733129382133484,-0.14508147537708282,-0.27356573939323425,0.09667808562517166,0.5831335186958313,-0.39006850123405457,-0.32520249485969543,0.1486770361661911,0.596431314945221,0.2794797420501709,0.2589181065559387,0.20109805464744568,-0.04366277530789375,-0.33193880319595337,-0.18556857109069824,0.1278470903635025,-0.20540101826190948,-0.3478020429611206,0.13794997334480286,0.3021399676799774,0.07850244641304016,-0.16799181699752808,-0.09806189686059952,-0.7960830330848694,0.3486948609352112,-0.09336826205253601,0.01516177412122488,-0.04708968475461006,0.1581602394580841,-0.8022424578666687,0.03138527646660805,0.4909176230430603,0.2877458333969116,0.841572642326355,0.5661733150482178,0.026635462418198586,-0.30074042081832886,0.12847094237804413,0.123040109872818,-0.530357301235199,-0.1851334422826767,-0.20262807607650757,-0.1722419112920761,-0.6264632940292358,0.21512742340564728,0.098024383187294,-0.09298866987228394,0.19545327126979828,0.07659254223108292,-0.5697728991508484,0.10743097215890884,-0.062289703637361526,-0.37136444449424744,0.17658504843711853,-0.1995491087436676,0.6000896096229553,0.5446431636810303,0.09060680121183395,0.3746317923069,0.17448106408119202,-0.2762659192085266,0.18328621983528137,0.2488306164741516,0.332749605178833,0.5783970952033997,-0.037576738744974136,0.04518624767661095,-0.3115343451499939,-0.25913920998573303,-0.08271718770265579,-0.21460676193237305,0.04562339931726456,-0.12538065016269684,0.06330040097236633,-0.5473999381065369,0.40281471610069275,0.08643703162670135,0.39010316133499146,-0.28707507252693176,-0.3988698124885559,0.2548975944519043,-0.596244752407074,-0.36296090483665466,0.09106028825044632,0.08628059178590775,-0.006753796245902777,0.2790062129497528,-0.007822655141353607,-0.2183188498020172,0.11900007724761963,-0.3553236126899719,0.045515257865190506,-0.04543730989098549,-0.4334217607975006,0.5030171871185303,0.2963714003562927,0.46367424726486206,0.11372742056846619,0.04395965859293938,0.0558110810816288,-0.07551019638776779,0.2103116810321808,0.4768654704093933,-0.09549561142921448,0.25818178057670593,0.06725899875164032,-0.019076596945524216,0.6436035633087158,0.43115702271461487,-0.18409587442874908,0.27460479736328125,-0.11279553920030594,0.3628086745738983,0.8756391406059265,-0.16569632291793823,-0.5725592970848083,-0.46491965651512146,-0.10880227386951447,-0.38210707902908325,0.5629875063896179,0.4668324887752533,-0.005056960973888636,0.39721783995628357,-0.17930299043655396,0.032091252505779266,-0.1734149008989334,0.1514834612607956,-0.17266187071800232,0.030231183394789696,0.16179947555065155,0.016173871234059334,-0.3889567255973816,-0.040105730295181274,0.6852182149887085,-0.17056332528591156,0.009471628814935684,0.06839419156312943,-0.19272325932979584,0.43498924374580383,-0.4185730218887329,-0.0691608116030693,0.13549940288066864,0.20263530313968658,-0.7055550813674927,0.045620158314704895,0.237683966755867,0.08215581625699997,-0.5321542024612427,-0.11966626346111298,-0.03687354922294617,0.35406091809272766,-0.10114505141973495,-0.19644716382026672,0.11994656920433044,0.4310673177242279,0.10448838770389557,-0.2917304039001465,-0.1504366099834442,-0.45104047656059265,-0.02311554364860058,-0.949122428894043,0.21165481209754944,-0.5899384617805481,-0.47168368101119995,-0.24085988104343414,0.05972730740904808,0.3302343487739563,0.4752365052700043,0.24450445175170898,0.13031023740768433,0.21393990516662598,0.1312989890575409,-0.03282894939184189,-0.37025073170661926,0.9061359167098999,-0.3247905373573303,-0.2214929610490799,-0.06802240759134293,0.38752731680870056,0.22081179916858673,-0.06486323475837708,-0.13878779113292694,0.2149602770805359,-0.282511442899704,-0.005793043877929449,-0.008571905083954334,-0.07864461839199066,-0.03404936194419861,0.2815157175064087,0.7811434268951416,0.10972055792808533,0.05166945978999138,-0.18611712753772736,0.05052011087536812,-0.12631236016750336,-0.3022436797618866,-0.46150144934654236,-0.0779104009270668,0.34365150332450867,0.14803551137447357,0.12991277873516083,0.825792670249939,0.275755375623703,0.23675240576267242,-0.3137243092060089,-0.17040173709392548,0.12642011046409607,-0.4852963984012604,-0.24567778408527374,0.08773858845233917,-0.238772913813591,0.23663853108882904,-0.017374536022543907,0.2082015424966812,0.18231184780597687,-0.47937068343162537,0.04966994747519493,-0.1949356645345688,0.205975741147995,0.0025467819068580866,0.2701561748981476,0.7731509804725647,0.3164472281932831,-0.15994179248809814,-0.9011840224266052,0.22056542336940765,-0.6061382293701172,0.36568400263786316,-0.4117090106010437,0.04804060980677605,-0.11520306766033173,0.4594838619232178,0.20422719419002533,0.07354438304901123,0.3978215157985687,-0.031201917678117752,0.1819244921207428,0.056023892015218735,-1.0529476404190063,0.1519877165555954,0.016519689932465553,0.20343197882175446,-0.021505847573280334,-0.20666085183620453,0.025366568937897682,0.1959206908941269,-0.08696545660495758,-0.05920695513486862,0.09881158173084259,0.014670287258923054,-0.3303206264972687,0.14015771448612213,0.17183029651641846,0.09901764988899231,0.10118337720632553,-0.03027333877980709,0.004650127608329058,-0.1635909229516983,0.43500885367393494,-0.11208578199148178,-0.13150455057621002,-0.1311725378036499,-0.10174199938774109,0.3829226791858673,0.23781366646289825,-0.06576218456029892,-0.4065907895565033,0.2317325472831726,-0.1530977487564087,-0.31642094254493713,-0.14991822838783264,0.17603859305381775,-0.0852842777967453,0.14920973777770996,-0.29430732131004333,0.1010172963142395,0.14003680646419525,-0.5138708353042603,-0.4377523958683014,0.018791567534208298,-0.2894686162471771,0.07399823516607285,-0.07216930389404297,0.7826613783836365,-0.3118347227573395,0.05137979984283447,-0.10354571789503098,-0.9213747382164001,-0.2112434357404709,-0.04582901671528816,0.26522329449653625,-0.11340198665857315,0.2189415842294693,0.11702308803796768,-0.12345701456069946,0.4716200530529022,0.20077943801879883,0.05351176857948303,-0.1546216905117035,-0.040615420788526535,-0.17661608755588531,-0.11938579380512238,0.03299933299422264,0.20597006380558014,-0.34591397643089294,-0.3740381896495819,-0.2550712823867798,0.08023053407669067,0.39799967408180237,0.31080588698387146,-0.3875563442707062,0.14988243579864502,-0.3040176331996918,0.35370585322380066,-0.24330469965934753,-1.034345269203186,0.0007306283223442733,-0.0303080752491951,0.09888232499361038,0.41571512818336487,0.1907341182231903,-0.4918035566806793,0.08092033118009567,0.10470251739025116,0.14376427233219147,0.4635019898414612,-0.3642641305923462,-0.19679929316043854,0.17440161108970642,-0.025394927710294724,0.2998369038105011,0.2736603915691376,0.6301887631416321,-0.002253464423120022,0.3055797517299652,-0.0073923757299780846,0.6265393495559692,-0.41688472032546997,-0.009258124977350235,0.03862685337662697,0.5144359469413757,0.0470881313085556,-0.3732745051383972,-0.6322953701019287,-0.5490356683731079,0.14011122286319733,0.289493203163147,-0.18810215592384338,0.2988987863063812,-0.09124613553285599,-0.3692929744720459,-0.22149746119976044,-0.2075560986995697,0.3984801173210144,-0.00962921604514122,-0.292996346950531,0.18000324070453644,-0.13189667463302612,-0.051924917846918106,-0.12057273089885712,-0.16992901265621185,0.41823717951774597,0.33166876435279846,-0.4061060845851898,-0.45943373441696167,-0.14989008009433746,-0.2384185642004013,-0.14589577913284302,0.14223071932792664,-0.08020590245723724,-0.07247916609048843,0.14955571293830872,0.6515206694602966,-0.8052490949630737,-0.2980805039405823,0.20758336782455444,-0.04584909975528717,-0.37851467728614807,-0.17733317613601685,0.06255055963993073,0.08746436983346939,-0.03260647878050804,-0.09400751441717148,0.09780365228652954,0.3111101984977722,-0.1523161679506302,-0.14678920805454254,0.005829953588545322,0.3404020369052887,0.2958231568336487,-0.20389871299266815,0.2092093974351883,0.22977913916110992,-0.08447016775608063,0.2299777865409851,0.0751592144370079,-0.29348695278167725,0.44462257623672485,0.11388316750526428,-0.2892463803291321,0.1528363823890686,-0.1815500557422638,0.43130385875701904,-0.09877090156078339,0.04231702908873558,-0.26913872361183167,-0.19084103405475616,-0.17178823053836823,0.2382560670375824,0.2730002999305725,-0.17198753356933594,-0.1840154230594635,0.10237786918878555,0.16107334196567535,0.3700719177722931,0.02101692371070385,0.5771474242210388,0.3239399194717407,-0.07348226010799408,0.1936970055103302,0.4810527563095093,-0.0008458044612780213,-0.11021077632904053,-0.05880902707576752,-0.14229199290275574,0.209275022149086,0.07920742779970169,-0.0010211458429694176,-0.4642699956893921,-0.2184097021818161,0.17658750712871552,-0.02354777604341507,0.2580026090145111,-0.09462568163871765,0.2122960239648819,0.4857681393623352,-0.28159162402153015,-0.05234367027878761,0.5735015869140625,0.00005084325312054716,-0.11893532425165176,0.40956443548202515,-0.05383187532424927,-0.3699478805065155,-0.24781925976276398,-0.24578125774860382,0.14393603801727295,-0.15967720746994019,0.7654747366905212,-0.22471724450588226,0.045930542051792145,0.17979244887828827,0.38298097252845764,0.03679696097970009,-0.29590290784835815,-0.04382762685418129,0.05563027411699295,0.21575868129730225,0.25657153129577637,0.14230576157569885,0.03170457482337952,-0.24406200647354126,0.1467740386724472,0.27860161662101746,0.43491023778915405,-0.0404534712433815,0.370902955532074,-0.4176679253578186,-0.1785939484834671,0.22974823415279388,-0.07810110598802567,-0.035804975777864456,0.2574838399887085,-0.1822066605091095,-0.6326085925102234,-0.19558556377887726,-0.07541385293006897,0.774126410484314,0.26518192887306213,0.19447271525859833,0.2005809098482132,0.3069532513618469,0.12512581050395966,-0.2525806725025177,-0.020766498520970345,-0.10959985107183456,-0.2347990721464157,-0.12566536664962769,-0.07513097673654556,-0.5344120264053345,0.05924713611602783,-0.05397321283817291,-0.7449734807014465,0.17542916536331177,0.25023770332336426,0.26052752137184143,-0.019489336758852005,-0.23805400729179382,0.14157460629940033,0.24171464145183563,0.1534891426563263,0.02004282921552658,0.0717519149184227,0.2878381907939911,-0.18915961682796478,0.6373456716537476,0.09025207906961441,-0.7283260822296143,0.36479660868644714,0.3669675588607788,0.24970589578151703,0.12170977890491486,0.1656051129102707,0.3020545244216919,0.1843757927417755,-0.27681857347488403,-0.21121081709861755,0.328060120344162,0.006554767955094576,0.009389997459948063,0.3259059190750122,0.23345421254634857,-0.2567698657512665,-0.0634554997086525,-0.30981817841529846,0.12847016751766205,0.19226102530956268,0.05541623383760452,0.27753394842147827,-0.17456237971782684,-0.24710823595523834,0.2637716233730316,0.17358747124671936,-0.1103171706199646,0.468788206577301,0.14961081743240356,-0.07724181562662125,-0.023111237213015556,0.02299543283879757,-0.2812124788761139,-0.2280803918838501,0.1501358300447464,-0.006851362995803356,-0.5014322400093079,-0.3299799859523773,0.39223891496658325,0.18194501101970673,0.3288871943950653,-0.5658308267593384,0.09503109753131866,0.35358747839927673,-0.17142783105373383,0.0016059564659371972,0.11485858261585236,-0.2991650700569153,0.32618871331214905,-0.10385967046022415,-0.2356875091791153,0.17863407731056213,0.37859097123146057,-0.019163280725479126,0.21005932986736298,-0.17014196515083313,0.06959950178861618,0.3780946433544159,0.45290035009384155,0.01785172149538994,0.2959460914134979,-0.26444241404533386,0.3028077185153961,0.17692406475543976,0.40959396958351135,-0.08668555319309235,-0.08858231455087662,0.07189086079597473,0.2636328339576721,-0.3054516911506653,-0.008768572472035885,-0.30403614044189453,-0.14135776460170746,0.21259932219982147,-0.2468237280845642,0.1314481794834137,0.2406366467475891,0.002132018329575658,0.07045983523130417,-0.07247358560562134,-0.12160832434892654,-0.1619480848312378,-0.007343824952840805,0.5794689059257507,-0.20310081541538239,-0.3700833320617676,0.19902320206165314,-0.205220028758049,-0.07274794578552246,0.2525670826435089,-0.7649275064468384,-0.053691357374191284,0.2405700832605362,-0.06440329551696777,0.09584909677505493,-0.10909843444824219,0.34338074922561646,0.03936019167304039,0.38218966126441956,0.009451129473745823,0.40133270621299744,-0.6321864128112793,-0.039728738367557526,-0.013293437659740448,-0.39357268810272217,0.2480500340461731,0.34015631675720215,-0.3719404339790344,0.43713366985321045,0.6204057335853577,-0.1596597284078598,0.6261811852455139,-0.22433677315711975,-0.19201958179473877,0.25640350580215454,-0.630264937877655,-0.6106865406036377,0.14009743928909302,-0.6457542181015015,0.028262587264180183,0.07856617867946625,0.24737221002578735,0.3716137111186981,0.6586434841156006,-0.0641447976231575,-0.4501134157180786,0.23109710216522217,0.005241159349679947,0.012399452738463879,-0.053972240537405014,-0.3941287100315094,-0.1388777494430542,-0.24154312908649445,0.1317872554063797,0.3870938718318939,0.3619173467159271,0.13871003687381744,-0.2198779582977295,-0.0649278312921524,0.08702220022678375,-0.33143746852874756,0.06574417650699615,-0.07006359100341797,0.11432693153619766,-0.40060174465179443,0.01598365046083927,-0.11894140392541885,0.46502193808555603,0.3950856924057007,0.20526261627674103,-0.44164806604385376,-0.3280986547470093,0.048655856400728226,-0.004729420877993107,-0.2933923602104187,-0.006849890109151602,-0.5804605484008789,-0.2868586778640747,-0.6345005631446838,0.060347169637680054,0.3162649869918823,-0.047816772013902664,-0.04491975158452988,0.12230898439884186,0.27738359570503235,0.3621819019317627,0.005763021297752857,-0.20510073006153107,0.33451250195503235,0.4245380461215973,0.03290078788995743,0.20016281306743622,-0.30608153343200684,0.09284724295139313,0.2708996534347534,0.3560333251953125,-0.1833864003419876,-0.38958191871643066,-0.2309240996837616,0.08937786519527435,-0.04164429381489754,-0.08073553442955017,0.5996442437171936,0.24368102848529816,-0.5735436081886292,0.10541227459907532,-0.21167027950286865,-0.09131886065006256,0.15293562412261963,0.1482173651456833,-1.086819052696228,-0.038654014468193054,-0.05649825185537338,0.36544540524482727,-0.4324814975261688,0.4434499144554138,0.0987212061882019,-0.2027316391468048,0.10891143232584,-0.46416419744491577,-0.013763396069407463,0.3113374412059784,0.139028862118721,0.33838343620300293,-0.26678991317749023,0.17052389681339264,0.24533259868621826,0.11522988229990005,-0.1531408727169037,-0.06307805329561234,-0.19827671349048615,-0.16325496137142181,-0.19863396883010864,-0.5358493328094482,0.14793354272842407,-0.26542407274246216,-0.15795393288135529}'

In [ ]:
sync_connection.close()

In [ ]:
await connection.close()